import { Product } from "@/types/product";

export const ADS_DATA: Product[] = [
  {
    id: "1",
    price: 800,
    title: "Milever All Season Versat MC545",
    location: "Baki",
    date: "Bu gün 18:55",
    image: "/images/products/thumb.jpg",
    isPremium: true,
  },
  {
    id: "2",
    price: 1450,
    title: "TOPRAN 502 184 Link set, wheel suspension for BMW 5 Series",
    location: "Baki",
    date: "Bu gün 18:55",
    image: "/images/products/thumb2.jpg",
    isPremium: true,
  },
  {
    id: "3",
    price: 355,
    title: "MOBILETRON VR-LC111 Alternator Regulator",
    location: "Baki",
    date: "Bu gün 18:55",
    image: "/images/products/thumb3.jpg",
  },
  {
    id: "4",
    price: 25,
    title: "LIQUI MOLY 3810 Housing / Flange Sealing Substance",
    location: "Baki",
    date: "Bu gün 18:55",
    image: "/images/products/thumb4.jpg",
  },
  {
    id: "5",
    price: 137,
    title: "VAN WEZEL 0301563 Bumper for AUDI A1",
    location: "Baki",
    date: "Bu gün 18:55",
    image: "/images/products/thumb5.jpg",
  },
  {
    id: "6",
    price: 241,
    title: "FEBI BILSTEIN 19934 Clamp, silencer",
    location: "Baki",
    date: "Bu gün 18:55",
    image: "/images/products/thumb6.jpg",
    isPremium: true,
  },
  {
    id: "7",
    price: 63,
    title: "VAICO V42-0391 Clamp, silencer",
    location: "Baki",
    date: "Bu gün 18:55",
    image: "/images/products/thumb7.jpg",
    isPremium: true,
  },
  {
    id: "8",
    price: 348,
    title: "BRINK 380000 Towbar suitable for JEEP GRAND CHEROKEE, COMMANDER",
    location: "Baki",
    date: "Bu gün 18:55",
    image: "/images/products/thumb8.jpg",
    isPremium: true,
  },
  {
    id: "9",
    price: 46,
    title: "FEBI BILSTEIN 31782 Crankshaft pulley",
    location: "Baki",
    date: "Bu gün 18:55",
    image: "/images/products/thumb9.jpg",
  },
  {
    id: "10",
    price: 3564,
    title: "BROCK B41 20 inch black alloy wheel",
    location: "Baki",
    date: "Bu gün 18:55",
    image: "/images/products/thumb10.jpg",
  },
];
