const RAW_CATEGORIES = [
  {
    id: "engine-oil",
    name: "Engine oil",
    img: "",
    subCategories: [],
  },
  {
    id: "tyres",
    name: "Tyres",
    img: "",
    subCategories: [],
  },
  {
    id: "oils-and-fluids",
    name: "Oils and fluids",
    img: "",
    subCategories: [
      "Automatic gearbox oil change kit",
      "Automatic transmission fluid",
      "Brake fluid",
      "Differential oil",
      "Engine coolant",
      "Engine oil",
      "Fuel additives",
      "Gearbox oil and transmission fluid",
    ],
  },
  {
    id: "brakes",
    name: "Brakes",
    img: "",
    subCategories: [
      "ABS sensor",
      "Accessory kit, brake shoes",
      "Brake caliper",
      "Brake caliper carrier",
      "Brake caliper piston",
      "Brake caliper repair kit",
      "Brake disc back plate",
      "Brake disc bolts",
      "Brake discs",
      "Brake fluid",
      "Brake hose",
      "Brake light switch",
      "Brake pad fitting kit",
      "Brake pad wear sensor",
      "Brake pads",
      "Brake pads and discs",
      "Brake servo",
      "Brake shoe adjuster",
      "Brake shoes",
      "Brake tools",
      "Drum brake",
      "Guide sleeve kit, brake caliper",
      "Handbrake",
      "Handbrake cable",
      "Handbrake shoes",
      "High-performance brake pads",
      "Master cylinder",
      "Multi-purpose grease",
      "Performance brake discs",
    ],
  },
  {
    id: "filters",
    name: "Filters",
    img: "",
    subCategories: [
      "Air filter",
      "Automatic gearbox oil change kit",
      "Automatic transmission filter",
      "Cabin filter",
      "Fuel filter",
      "Oil filter",
      "Oil filter housing",
      "Receiver drier",
      "Service kit",
    ],
  },
  {
    id: "engine",
    name: "Engine",
    img: "",
    subCategories: [
      "Accelerator pedal position sensor",
      "Air filter",
      "Boost pressure sensor",
      "Camshaft",
      "Camshaft adjuster",
      "Camshaft adjustment valve",
      "Camshaft gear",
      "Camshaft sensor",
      "Coolant flange",
      "Coolant temperature sensor",
      "Crankcase breather hose",
      "Crankcase gasket",
      "Crankshaft bearing",
      "Crankshaft pulley",
      "Crankshaft seal",
      "Crankshaft sensor",
      "Cylinder head",
      "Cylinder head gasket set",
      "Drive belt tensioner",
      "Drive chain",
      "Engine control unit (ECU)",
      "Engine coolant",
      "Engine electrics",
      "Engine mount",
      "Engine oil",
      "Engine tools",
      "Exhaust manifold gasket",
      "Exhaust valve",
      "Expansion tank",
      "Expansion tank cap",
      "Flywheel",
      "Flywheel bolt",
      "Fuel filter",
      "Fuel pressure sensor",
      "Full engine gasket set",
      "Head bolts",
      "Head gasket",
      "High pressure fuel pump (HPFP)",
      "Idler pulley, serpentine belt",
      "Ignition coil",
      "Injector seals",
      "Injectors",
      "Inlet valves",
      "Intake air control valve",
      "Intake manifold",
      "Intake manifold gasket",
      "Intercooler",
      "Intercooler pipe",
      "Knock sensor",
      "Lambda sensor",
      "Main bearings, crankshaft",
      "Manifold absolute pressure (MAP) sensor",
      "Mass air flow sensor (MAF)",
      "Mounting kit, charger",
      "Oil cap",
      "Oil cooler",
      "Oil cooler gasket",
      "Oil drain plug gasket",
      "Oil filter",
      "Oil level sensor",
      "Oil sump",
      "Oil temperature sensor",
      "PCV valve",
      "Piston",
      "Piston rings",
      "Poly v-belt kit",
      "Pulley bolt",
      "Radiator",
      "Radiator fan",
      "Rocker arm",
      "Rocker cover",
      "Rocker cover breather pipe",
      "Rocker cover gasket",
      "Seal, crankcase breather",
      "Seal, turbo air hose",
      "Serpentine belt",
      "Skid plate",
      "Spark plugs",
      "Sump gasket",
      "Sump plug",
      "Tappet",
      "Tensioner pulley, v-ribbed belt",
      "Thermostat",
      "Throttle body",
      "Timing chain",
      "Timing chain kit",
      "Timing cover gasket",
      "Turbo",
      "Turbo gasket",
      "Turbo oil feed pipe",
      "Valve cotter",
      "Valve guides",
      "Valve stem seals",
      "Water pump",
      "Water pump + serpentine belt kit",
    ],
  },
  {
    id: "wiper-and-washer-system",
    name: "Wiper and washer system",
    img: "",
    subCategories: [
      "Headlight washer",
      "Indicator stalk",
      "Rain sensor",
      "Water pump, headlight cleaning",
      "Windscreen washer jets",
      "Windscreen washer pump",
      "Windscreen washer reservoir",
      "Wiper arm",
      "Wiper blades",
    ],
  },
  {
    id: "ignition-and-preheating",
    name: "Ignition and preheating",
    img: "",
    subCategories: [
      "Camshaft sensor",
      "Crankshaft sensor",
      "Engine control unit (ECU)",
      "Ignition coil",
      "Knock sensor",
      "Preheating / ignition tools",
      "Spark plugs",
      "Timing cover gasket",
    ],
  },
  {
    id: "suspension",
    name: "Suspension",
    img: "",
    subCategories: [
      "ABS sensor",
      "Anti-roll bar bushes",
      "Anti-roll bar link",
      "Anti-roll bar stabiliser kit",
      "Axle bushes",
      "Ball joint",
      "Camber bolts",
      "Engine mount",
      "Gearbox mount",
      "Headlight level sensor",
      "Inner tie rod",
      "Locking wheel bolts",
      "Repair kit, wheel suspension",
      "Shock absorber dust cover and bump stops",
      "Steering knuckle bushing",
      "Steering rack boot",
      "Suspension arm",
      "Suspension bushes",
      "Suspension kit",
      "Suspension tools",
      "Sway bar",
      "Top strut mount and bearing",
      "Track rod end",
      "Tyre pressure sensor (TPMS)",
      "Wheel bearing",
      "Wheel bolts and wheel nuts",
      "Wheel hub",
      "Wheel spacers",
    ],
  },
  {
    id: "electrics",
    name: "Electrics",
    img: "",
    subCategories: [
      "ABS sensor",
      "AC pressure switch",
      "Accelerator pedal position sensor",
      "Alternator",
      "Battery",
      "Boost pressure sensor",
      "Boot light",
      "Brake light bulb",
      "Brake light switch",
      "Brake pad wear sensor",
      "Camshaft adjustment valve",
      "Camshaft sensor",
      "Central locking",
      "Clutch switch",
      "Combination rearlight bulb",
      "Coolant temperature sensor",
      "Crankshaft sensor",
      "Daytime running lights",
      "Engine control unit (ECU)",
      "Exhaust pressure sensor (DPF)",
      "Fog light bulb",
      "Fog lights",
      "Fuel pressure sensor",
      "Fuel pump relay",
      "Fuse",
      "Fuse box / -holder",
      "Headlight bulb",
      "Headlight control module",
      "Headlight motor",
      "Headlight parts",
      "Heater resistor",
      "Horn",
      "Indicator",
      "Indicator bulb",
      "Indicator stalk",
      "Interior lights",
      "Interior temperature sensor",
      "Knock sensor",
      "Lambda sensor",
      "Lighting controls",
      "Manifold absolute pressure (MAP) sensor",
      "Mass air flow sensor (MAF)",
      "Multifunctional relay",
      "Number plate bulb",
      "Number plate light",
      "Oil level sensor",
      "Oil temperature sensor",
      "Outside temperature sensor",
      "Parking light",
      "Parking sensors",
      "Radiator fan motor",
      "Reflectors",
      "Reverse light bulb",
      "Spotlight bulb",
      "Starter motor",
      "Third brake light",
      "Towbar electric kit",
      "Transmission control module",
      "Tyre pressure sensor (TPMS)",
      "Window regulator",
      "Windscreen washer pump",
      "Wiring harness",
      "Xenon light",
    ],
  },
  {
    id: "damping",
    name: "Damping",
    img: "",
    subCategories: [
      "Camber bolts",
      "Coil spring",
      "Repair kit, wheel suspension",
      "Shock absorber",
      "Shock absorber dust cover and bump stops",
      "Suspension kit, coil springs",
      "Suspension kit, shock absorber and coil spring",
      "Suspension Strut",
      "Top strut mount and bearing",
    ],
  },
  {
    id: "belts-chains-rollers",
    name: "Belts, chains, rollers",
    img: "",
    subCategories: [
      "Belt / chain tools",
      "Crankshaft pulley",
      "Drive belt tensioner",
      "Drive chain",
      "Idler pulley, serpentine belt",
      "Poly v-belt kit",
      "Pulley bolt",
      "Serpentine belt",
      "Tensioner pulley, v-ribbed belt",
      "Timing chain",
      "Timing chain kit",
      "Water pump",
    ],
  },
  {
    id: "engine-cooling-system",
    name: "Engine cooling system",
    img: "",
    subCategories: [
      "Coolant flange",
      "Coolant temperature sensor",
      "Engine coolant",
      "Expansion tank",
      "Expansion tank cap",
      "Intercooler",
      "Oil cooler",
      "Oil cooler gasket",
      "Oil temperature sensor",
      "Poly v-belt kit",
      "Radiator",
      "Radiator fan",
      "Radiator fan motor",
      "Radiator hose",
      "Seal ring for coolant pipe",
      "Thermostat",
      "Water pump",
    ],
  },
  {
    id: "body",
    name: "Body",
    img: "",
    subCategories: [
      "Bonnet",
      "Bonnet struts",
      "Boot lock",
      "Boot struts",
      "Brake light bulb",
      "Bumper",
      "Bumper brackets",
      "Bumper grill",
      "Bumper trim",
      "Central locking",
      "Combination rearlight bulb",
      "Cross beam",
      "Daytime running lights",
      "Door handle",
      "Door lock",
      "Door trim",
      "Engine cover",
      "Fender flares",
      "Fog light bulb",
      "Fog light cover",
      "Fog lights",
      "Front grill",
      "Front splitter",
      "Fuel tank and fuel tank cap",
      "Fuel tank breather valve",
      "Headlight bulb",
      "Headlight parts",
      "Holder, park assist sensor",
      "Indicator",
      "Indicator bulb",
      "Jacking point",
      "Number plate bulb",
      "Number plate light",
      "Parking light",
      "Parking sensors",
      "Radiator support",
      "Rear door",
      "Reflectors",
      "Reverse light bulb",
      "Rocker panel",
      "Side panel",
      "Side window",
      "Skid plate",
      "Spotlight bulb",
      "Spotlights",
      "Third brake light",
      "Tow hook cover",
      "Under bonnet insulation",
      "Wheel arch liner",
      "Window seal",
      "Windscreen",
      "Wing",
      "Wing mirror",
      "Wing mirror cover",
      "Wing mirror glass",
      "Xenon light",
    ],
  },
  {
    id: "heating-and-ventilation",
    name: "Heating and ventilation",
    img: "",
    subCategories: [
      "Air recirculation flap motor",
      "Blower motor",
      "Cabin filter",
      "Heater matrix",
      "Heater resistor",
      "Interior temperature sensor",
      "Outside temperature sensor",
    ],
  },
  {
    id: "gaskets-and-sealing-rings",
    name: "Gaskets and sealing rings",
    img: "",
    subCategories: [
      "Crankcase gasket",
      "Crankshaft seal",
      "Differential seal",
      "Exhaust gasket",
      "Exhaust manifold gasket",
      "Fuel pump gasket",
      "Full engine gasket set",
      "Gearbox oil seal",
      "Head gasket",
      "Injector seals",
      "Intake manifold gasket",
      "Mounting kit, charger",
      "Oil cooler gasket",
      "Oil drain plug gasket",
      "Rocker cover gasket",
      "Seal ring for coolant pipe",
      "Seal, crankcase breather",
      "Sump gasket",
      "Timing cover gasket",
      "Turbo gasket",
      "Valve stem seals",
      "Window seal",
    ],
  },
  {
    id: "exhaust",
    name: "Exhaust",
    img: "",
    subCategories: [
      "Boost pressure sensor",
      "Catalytic converter",
      "Clamp, exhaust system",
      "Exhaust clamp",
      "Exhaust gasket",
      "Exhaust hanger",
      "Exhaust manifold gasket",
      "Exhaust pipe",
      "Exhaust pressure sensor (DPF)",
      "Intercooler",
      "Intercooler pipe",
      "Lambda sensor",
      "Middle silencer",
      "Mounting kit, exhaust system",
      "Turbo",
      "Turbo gasket",
      "Turbo oil feed pipe",
    ],
  },
  {
    id: "interior",
    name: "Interior",
    img: "",
    subCategories: [
      "Accelerator pedal",
      "Accelerator pedal position sensor",
      "Boot",
      "Boot light",
      "Boot struts",
      "Brake light switch",
      "Central locking",
      "Clutch switch",
      "Door handle",
      "Door lights",
      "Door lock",
      "Floor mats",
      "Gear stick knob",
      "Heater resistor",
      "Indicator stalk",
      "Interior lights",
      "Interior temperature sensor",
      "Lighting controls",
      "Multifunctional relay",
      "Outside temperature sensor",
      "Parking sensors",
      "Pedals and pedal covers",
      "Rain sensor",
      "Window regulator",
    ],
  },
  {
    id: "fuel-supply-system",
    name: "Fuel supply system",
    img: "",
    subCategories: [
      "Accelerator pedal",
      "Accelerator pedal position sensor",
      "Engine control unit (ECU)",
      "Fuel cap",
      "Fuel filter",
      "Fuel pressure sensor",
      "Fuel pump",
      "Fuel pump gasket",
      "Fuel pump relay",
      "Fuel tank and fuel tank cap",
      "Fuel tank breather valve",
      "High pressure fuel pump (HPFP)",
      "In-tank fuel pump",
      "Injector seals",
      "Injectors",
      "Knock sensor",
      "Lambda sensor",
      "Mass air flow sensor (MAF)",
      "Oil filter housing",
      "Throttle body",
    ],
  },
  {
    id: "steering",
    name: "Steering",
    img: "",
    subCategories: [
      "Ball joint",
      "Inner tie rod",
      "Steering column universal joint",
      "Steering rack",
      "Steering rack boot",
      "Steering tools",
      "Tie rod",
      "Track rod end",
    ],
  },
  {
    id: "clutch",
    name: "Clutch",
    img: "",
    subCategories: [
      "Clutch kit",
      "Clutch master cylinder",
      "Clutch plate",
      "Clutch pressure plate",
      "Clutch release bearing",
      "Clutch slave cylinder",
      "Clutch switch",
      "Clutch tools",
      "Flywheel",
      "Flywheel bolt",
      "Pedals and pedal covers",
    ],
  },
  {
    id: "drive-shaft-and-cv-joint",
    name: "Drive shaft and cv joint",
    img: "",
    subCategories: [
      "Cv boot",
      "Cv joint",
      "Drive shaft",
      "Intermediate shaft bearing",
    ],
  },
  {
    id: "wheels",
    name: "Wheels",
    img: "",
    subCategories: [],
  },
  {
    id: "towbar-parts",
    name: "Towbar / parts",
    img: "",
    subCategories: ["Tow hook cover", "Towbar", "Towbar electric kit"],
  },
  {
    id: "gearbox",
    name: "Gearbox",
    img: "",
    subCategories: [
      "Automatic gearbox oil change kit",
      "Automatic gearbox solenoid",
      "Automatic transmission filter",
      "Automatic transmission fluid",
      "Automatic transmission oil cooler",
      "Flywheel",
      "Gear stick knob",
      "Gearbox mount",
      "Gearbox oil and transmission fluid",
      "Gearbox oil seal",
      "Mounting, transfer gear",
      "Transmission control module",
      "Transmission oil pan",
    ],
  },
  {
    id: "air-conditioning",
    name: "Air conditioning",
    img: "",
    subCategories: [
      "AC compressor",
      "AC compressor valve",
      "AC pressure switch",
      "Air quality sensor",
      "Air recirculation flap motor",
      "Blower motor",
      "Cabin filter",
      "Compressor clutch",
      "Condenser",
      "Evaporator",
      "Expansion valve",
      "Heater matrix",
      "Heater resistor",
      "Interior temperature sensor",
      "Outside temperature sensor",
      "Receiver drier",
    ],
  },
  {
    id: "bearings",
    name: "Bearings",
    img: "",
    subCategories: [
      "Clutch release bearing",
      "Crankshaft bearing",
      "Intermediate shaft bearing",
      "Main bearings, crankshaft",
      "Propshaft bearing",
      "Wheel bearing",
    ],
  },
  {
    id: "propshafts-and-differentials",
    name: "Propshafts and differentials",
    img: "",
    subCategories: [
      "Automatic transmission fluid",
      "Centering bush, propshaft",
      "Differential parts",
      "Differential seal",
      "Gearbox oil and transmission fluid",
      "Mounting, transfer gear",
      "Propshaft",
      "Propshaft bearing",
      "Propshaft coupling",
    ],
  },
  {
    id: "sensors-relays-control-units",
    name: "Sensors, relays, control units",
    img: "",
    subCategories: [
      "ABS sensor",
      "AC compressor valve",
      "AC pressure switch",
      "Accelerator pedal position sensor",
      "Air quality sensor",
      "Boost pressure sensor",
      "Brake light switch",
      "Brake pad wear sensor",
      "Camshaft adjustment valve",
      "Camshaft sensor",
      "Coolant temperature sensor",
      "Crankshaft sensor",
      "Engine control unit (ECU)",
      "Exhaust pressure sensor (DPF)",
      "Fuel pressure sensor",
      "Fuel pump relay",
      "Headlight control module",
      "Headlight level sensor",
      "Headlight motor",
      "Heater resistor",
      "Intake air control valve",
      "Interior temperature sensor",
      "Knock sensor",
      "Lambda sensor",
      "Manifold absolute pressure (MAP) sensor",
      "Mass air flow sensor (MAF)",
      "Multifunctional relay",
      "Oil level sensor",
      "Oil temperature sensor",
      "Outside temperature sensor",
      "Parking sensors",
      "Temperature sensor",
      "Transmission control module",
      "Tyre pressure sensor (TPMS)",
      "Window regulator",
    ],
  },
  {
    id: "car-accessories",
    name: "Car accessories",
    img: "",
    subCategories: [],
  },
  {
    id: "repair-kits",
    name: "Repair kits",
    img: "",
    subCategories: [
      "Accessory kit, brake shoes",
      "Anti-roll bar stabiliser kit",
      "Brake caliper repair kit",
      "Guide sleeve kit, brake caliper",
      "Repair kit, automatic adjustment",
      "Repair kit, wheel suspension",
      "Suspension kit",
    ],
  },
  {
    id: "tools-equipment",
    name: "Tools & equipment",
    img: "",
    subCategories: [],
  },
  {
    id: "pipes-and-hoses",
    name: "Pipes and hoses",
    img: "",
    subCategories: [
      "Brake hose",
      "Coolant flange",
      "Crankcase breather hose",
      "Intercooler pipe",
      "Radiator hose",
      "Rocker cover breather pipe",
      "Seal, turbo air hose",
      "Turbo oil feed pipe",
    ],
  },
  {
    id: "auto-detailing-car-care",
    name: "Auto detailing & car care",
    img: "",
    subCategories: [],
  },
  {
    id: "lighting",
    name: "Lighting",
    img: "",
    subCategories: [
      "Additional lighting",
      "Boot light",
      "Brake light bulb",
      "Combination rearlight bulb",
      "Daytime running lights",
      "Door lights",
      "Fog light bulb",
      "Fog lights",
      "Headlight bulb",
      "Indicator",
      "Indicator bulb",
      "Interior lights",
      "Lighting controls",
      "Number plate bulb",
      "Number plate light",
      "Parking light",
      "Reverse light bulb",
      "Spotlight bulb",
      "Spotlights",
      "Xenon light",
    ],
  },
  {
    id: "tuning",
    name: "Tuning",
    img: "",
    subCategories: [
      "Chip tuning box",
      "Performance brake discs",
      "Performance clutch",
      "Racing brake pads",
      "Sport grille",
      "Sport suspension",
      "Wheel spacers",
    ],
  },
  {
    id: "fasteners",
    name: "Fasteners",
    img: "",
    subCategories: [
      "Clamps",
      "Nuts",
      "Rivets",
      "Screws",
      "Universal gaskets & O-rings",
    ],
  },
];

export const CATEGORIES = RAW_CATEGORIES.map((cat, i) => ({
  ...cat,
  img: `/images/catalog-icons/${i + 1}.svg`,
}));
