import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Filter from "@/components/Filter";
import TopParts from "@/components/TopParts";
import Footer from "@/components/Footer";
import TopCategory from "@/components/TopCategory";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="az">
      <body
        className={`${montserrat.variable} antialiased font-sans bg-white text-neutral-900`}
      >
        <Header />
        <TopCategory />
        <Filter />
        <TopParts />
        {children}
        <Footer />
      </body>
    </html>
  );
}
